import img4 from "../assets/Artboard 2 copy.jpg";

export const DOCTORS = [
  {
    id: "karim-nassar",
    nameAr: "د/ كريم نصار",
    nameEn: "Dr. Karim Nassar",
    specialtyAr: "نائب طب وجراحه العيون",
    specialtyEn: "Ophthalmology (Deputy Ophthalmic Surgeon)",
    degreeAr: "نائب طب وجراحه العيون",
    degreeEn: "Deputy of Ophthalmology",
    deptSlug: "ophthalmology",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: img4,
    bioAr:
      "عضو كليه الجراحين الملكية جلاسكو - نائب طب وجراحه العيون - فحوصات العيون التخصصيه باحدث الاجهزه الطبيه للاكتشاف المبكر و اعتلال الشبكيه والمياه الزرقاء و امراض القرنيه والقرنيه المخروطية و المياه البيضاء و عمي الالوان - فحص رخصه القياده. دكتور عيون متخصص في عيون اطفال، ليزك وتصحيح الابصار والمياة البيضاء وعيون بالغين.",
    bioEn:
      "Member of the Royal College of Surgeons (Glasgow). Deputy ophthalmic surgeon. Specialized eye examinations with the latest devices for early detection of diabetic retinopathy, glaucoma, corneal diseases and keratoconus, cataract, and color blindness; driver’s license vision test. Pediatric & adult ophthalmology, LASIK and refractive surgery, cataract."
  },

  {
    id: "omar-tawfik",
    nameAr: "د/ عمر توفيق",
    nameEn: "Dr. Omar Tawfik",
    specialtyAr: "إخصائي طب وجراحة العظام والعمود الفقري",
    specialtyEn: "Orthopedics & Spine Specialist",
    degreeAr: "ماجستير جراحة العظام والعمود الفقري",
    degreeEn: "MSc Orthopedic & Spine Surgery",
    deptSlug: "orthopedics",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr:
      "ماجستير جراحة العظام والعمود الفقري - عضو الجمعية السويسرية لجراحة العمود الفقري - علاج حالات الكسور - آلام العظام والمفاصل - إصابات الملاعب - خشونة المفاصل - الانزلاق الغضروفي - حقن المفاصل - الحقن الموضعي للعضلات والأربطة. دكتور عظام متخصص في عظام أطفال، جراحة عظام بالغين، عظام بالغين ومناظير مفاصل.",
    bioEn:
      "MSc Orthopedic & Spine Surgery. Member of the Swiss Spine Society. Manages fractures, bone & joint pain, sports injuries, osteoarthritis, disc herniation, intra-articular injections, and trigger point injections. Adult & pediatric orthopedics and arthroscopy."
  },

  {
    id: "heba-hashim",
    nameAr: "د/ هبه هاشم",
    nameEn: "Dr. Heba Hashim",
    specialtyAr: "أخصائية طب الأطفال وحديثى الولادة",
    specialtyEn: "Pediatrics & Neonatology Specialist",
    degreeAr: "ماجستير طب الأطفال وحديثي الولادة",
    degreeEn: "MSc Pediatrics & Neonatology",
    deptSlug: "pediatrics",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr:
      "اخصائية طب أطفال وحديثي الولادة - بكالوريوس الطب والجراحة جامعة الأزهر - ماجيستير طب الأطفال وحديثي الولادة جامعة الأزهر - خبرة 12 عام - تجري الفحوصات الطبية وتقييم الحالات البدنية والفسيولوجية للطفل - علاج أمراض حساسية الصدر المزمنة لدى الأطفال - فحص وتشخيص الأمراض المعدية - علاج حديثي الولادة من صعوبات التنفس والالتهابات وتقديم الرعاية اللازمة - مساعدة الأم في حل مشاكل الرضاعة الطبيعية.",
    bioEn:
      "Pediatrics & neonatology specialist, 12+ years of experience. Comprehensive pediatric assessments, management of pediatric asthma, diagnosis of infectious diseases, neonatal care for respiratory difficulties and infections, and breastfeeding guidance."
  },

  {
    id: "marwa-nabil",
    nameAr: "د/ مروة نبيل",
    nameEn: "Dr. Marwa Nabil",
    specialtyAr: "مقيم طب الأطفال وحديثي الولادة",
    specialtyEn: "General Pediatrics & Neonatology",
    degreeAr: "بكالوريوس الطب والجراحة جامعة طنطا - ماجستير طب الأطفال وحديثي الولادة",
    degreeEn: "MBBS Tanta University - MSc Pediatrics & Neonatology",
    deptSlug: "pediatric-er",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr:
      "بكالوريوس الطب والجراحة جامعة طنطا - خبرة عشر سنوات بالرياض. الكشف على جميع الأمراض المعدية وكتابة العلاج المناسب - متابعة حديثي الولادة وحالات الصفراء - المتابعة المبكرة لاضطرابات النمو والغدة الدرقية.",
    bioEn:
      "MBBS Tanta University. 10+ years in Riyadh. Manages infectious diseases, neonatal follow-up including jaundice, and early screening for growth disorders and thyroid issues."
  },

  {
    id: "may-alqurashi",
    nameAr: "أ/ مى القرشي",
    nameEn: "Ms. Mai Al-Qurashi",
    specialtyAr: "اخصائية تقنية أشعة",
    specialtyEn: "Radiology Technologist",
    degreeAr: "اخصائية تقنية أشعة",
    degreeEn: "Radiology Technologist",
    deptSlug: "radiology",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr: "اخصائية تقنية أشعة. خبرة في الأشعة العامة والإجراءات الروتينية.",
    bioEn: "Radiology technologist with experience in general imaging and routine radiographic procedures."
  },

  {
    id: "sarah-nazih",
    nameAr: "أ/ ساره نزيه",
    nameEn: "Ms. Sarah Nazih",
    specialtyAr: "أخصائي علاج طبيعي",
    specialtyEn: "Physiotherapy Specialist",
    degreeAr: "أخصائي علاج طبيعي",
    degreeEn: "Physiotherapy Specialist",
    deptSlug: "physiotherapy",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr: "أخصائي علاج طبيعي. تقييم وتأهيل حالات آلام الظهر والرقبة، إصابات الملاعب، وإعادة التأهيل بعد العمليات.",
    bioEn: "Physiotherapist specialized in assessment and rehabilitation for back/neck pain, sports injuries, and post-operative rehab."
  },

  {
    id: "salwan-hatem",
    nameAr: "د/ سلوان حاتم",
    nameEn: "Dr. Salwan Hatem",
    specialtyAr: "طبيب أسنان عام",
    specialtyEn: "General Dentist",
    degreeAr: "بكالوريس طب وجراحة الفم والأسنان",
    degreeEn: "Bachelor of Dental Medicine and Surgery (B.D.S.)",
    deptSlug: "dental",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr:
      "بكالوريس طب وجراحة الفم والأسنان - خبرة أكثر من 10 سنوات بالرياض. حشوات الأسنان التجميلية، عدسات الأسنان التجميلية، تركيبات الأسنان، تنظيف اللثة والأسنان، تبييض الأسنان وتوريد اللثة بالليزر.",
    bioEn:
      "BDS, 10+ years in Riyadh. Esthetic fillings, veneers, fixed/removable prosthodontics, scaling & polishing, laser whitening and gingival depigmentation."
  },

  {
    id: "ashraf-osman",
    nameAr: "د/ اشرف عثمان",
    nameEn: "Dr. Ashraf Osman",
    specialtyAr: "اخصائى الامراض الباطنية والسكر",
    specialtyEn: "Internal Medicine & Diabetes Specialist",
    degreeAr: "ماجيستير الباطنة العامة والجهاز الهضمي",
    degreeEn: "MSc Internal Medicine & Gastroenterology",
    deptSlug: "internal-med",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr:
      "اخصائى الامراض الباطنية والسكر - ماجيستير الباطنة العامة والجهاز الهضمي - مدرس مساعد بكلية طب الزقازيق (مصر) - الزمالة البريطانية في أمراض الباطنة - خبرة 15 عام في أمراض الباطنة والكلى وعلاج الأمراض المزمنة (الضغط، السكر، الغدة، القلب، الصدر).",
    bioEn:
      "Specialist in internal medicine & diabetes. MSc Internal Medicine & Gastroenterology. British fellowship in Internal Medicine. 15+ years’ experience managing chronic diseases (hypertension, diabetes, thyroid disorders, cardiac & respiratory conditions)."
  },

  {
    id: "malak-abdullah",
    nameAr: "د/ ملاك عبدالله شحاته",
    nameEn: "Dr. Malak Abdullah Shahata",
    specialtyAr: "أخصائي جراحة الأنف والأذن والحنجرة والرأس والعنق",
    specialtyEn: "ENT & Head-Neck Surgery Specialist",
    degreeAr: "ماجستير جراحة الأنف والأذن والحنجرة والرأس والعنق",
    degreeEn: "MSc ENT & Head-Neck Surgery",
    deptSlug: "ent",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr:
      "أخصائي جراحة الأنف والأذن والحنجرة والرأس والعنق. دكتور أنف وأذن وحنجرة متخصص في جراحة بالغين وحالات الأنف والجيوب والأذن والحنجرة.",
    bioEn:
      "Specialist in ENT & head-neck surgery. Adult ENT surgery, nasal/sinus, ear, and laryngeal conditions."
  },

  {
    id: "mohamed-halaby",
    nameAr: "د/ محمد الحلبي",
    nameEn: "Dr. Mohamed El-Halaby",
    specialtyAr: "أخصائي جراحة الفم وزراعة الأسنان",
    specialtyEn: "Oral Surgery & Implant Specialist",
    degreeAr: "ماجستير جراحة الفم",
    degreeEn: "MSc Oral Surgery",
    deptSlug: "dental",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr:
      "عضو الجمعية المصرية لزراعة الأسنان. ماجستير جراحة الفم بكلية طب الأسنان جامعة المنصورة. متخصص في علاج اللثة، حشو وعلاج الجذور والأعصاب، تجميل الأسنان، زراعة الأسنان، التركيبات، وجراحات الوجه والفكين.",
    bioEn:
      "Member of the Egyptian Society of Dental Implants. MSc Oral Surgery (Mansoura University). Specializes in periodontics, endodontics, esthetics, dental implants, prosthodontics, and oral & maxillofacial procedures."
  },

  {
    id: "eman-nada",
    nameAr: "د/ ايمان ندا",
    nameEn: "Dr. Eman Nada",
    specialtyAr: "اخصائية النساء والتوليد",
    specialtyEn: "OB/GYN Specialist",
    degreeAr: "ماجستير النساء والتوليد",
    degreeEn: "Master of Obstetrics and Gynecology",
    deptSlug: "obgyn",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr:
      "اخصائية النساء والتوليد - خبرة أكثر من 30 عام بالرياض. تتابع الحمل العادي وعالي المخاطر ومتابعة التبويض - متابعة متلازمة تكيسات المبايض - الإجهاض المتكرر - الالتهابات النسائية - تأخر الحمل للمرأة والرجل - متابعة فقر الدم وأنواعه - متابعة جميع الأمراض النسائية - عدم انتظام الدورة واضطراب الهرمونات - التجميل النسائي - الكشف المبكر عن سرطان عنق الرحم والثدي والفيروس الحليمي - وسائل تنظيم الحمل بأنواعها بما في ذلك اللولب الهرموني وشريحة منع الحمل.",
    bioEn:
      "OB/GYN specialist with 30+ years in Riyadh. High-risk pregnancy follow-up, ovulation tracking, PCOS management, recurrent miscarriage, infections, infertility (male & female), anemia follow-up, menstrual/ hormonal disorders, female aesthetic procedures, early screening for cervical & breast cancer (HPV), and all contraception methods including hormonal IUD and implants."
  },

  {
    id: "raneem-ahmed",
    nameAr: "د/ رنيم احمد",
    nameEn: "Dr. Raneem Ahmed",
    specialtyAr: "اخصائية الجلدية والتجميل والليزر",
    specialtyEn: "Dermatology, Aesthetics & Laser Specialist",
    degreeAr: "اخصائية الجلدية والتجميل والليزر",
    degreeEn: "Dermatology, Aesthetics & Laser Specialist",
    deptSlug: "dermatology-cosmetic",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr:
      "اخصائية الجلدية والتجميل والليزر - خبرة أكثر من 10 سنوات. تعالج: حقن البوتوكس والفيلر، مشاكل تساقط الشعر، حب الشباب وآثاره، علاج الثعلبة والبهاق والصدفية، التقشير البارد والكيميائي، الميزوثيرابي والبلازما، إزالة الثآليل بالكي البارد أو الليزر.",
    bioEn:
      "Dermatology & laser specialist with 10+ years of experience. Botox & fillers, hair loss, acne & scars, alopecia, vitiligo & psoriasis, chemical/cold peels, mesotherapy & PRP, and wart removal (cryo/laser)."
  },
  { id: "hessa-alrashid",
    nameAr: "د/ حصة الرشيد",
    nameEn: "Dr. Hessa Al-Rashid",
    specialtyAr: "استشاري النساء والتوليد",
    specialtyEn: "Consultant OB/GYN",
    degreeAr: "استشاري النساء والتوليد",
    degreeEn: "Consultant of Obstetrics and Gynecology",
    deptSlug: "obgyn",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr: "استشاري النساء والتوليد. متابعة حالات النساء والتوليد العامة والمتقدمة وجراحة الأورام النسائية.",
    bioEn: "Consultant obstetrics & gynecology. General and advanced OB/GYN care and gynecologic oncology surgery."
  },
  { id: "mohamed-abdel-moneim",
    nameAr: "د/ محمد عبد المنعم",
    nameEn: "Dr.Mohamed Abdel Moneim",
    specialtyAr: "طبيب عام وطوارئ",
    specialtyEn: "General Practitioner & Emergency Medicine",
    degreeAr: " طبيب عام وطوارئ ",
    degreeEn: "General Practitioner & Emergency Medicine",
    deptSlug: "general-er",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr: "طبيب عام وطوارئ يتمتع بخبرة واسعة في التعامل مع الحالات الحادة والمزمنة، وتشخيص الأمراض الباطنية والمعدية، وتقديم الرعاية الطبية الأولية والفحوصات الدورية. متخصص في التعامل مع حالات الطوارئ والإصابات البسيطة، ويمتلك مهارة عالية في اتخاذ القرارات السريعة لتقديم الرعاية المثلى للمرضى في أقصر وقت ممكن.",
    bioEn: "General practitioner & emergency medicine specialist with extensive experience in managing acute and chronic cases, diagnosing internal and infectious diseases, and providing primary medical care and routine check-ups. Skilled in handling emergency situations and minor injuries, with a high ability to make quick decisions to provide optimal patient care in the shortest time possible."
  },
  { id: "wael-moussa",
    nameAr: "د/ وائل موسي ",
    nameEn: "Dr.Wael Moussa",
    specialtyAr: "طبيب عام وطوارئ",
    specialtyEn: "General Practitioner & Emergency Medicine",
    degreeAr: "طبيب عام وطوارئ",
    degreeEn: "General Practitioner & Emergency Medicine",
    deptSlug: "general-er",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr: "طبيب عام وطوارئ يتمتع بخبرة واسعة في التعامل مع الحالات الحادة والمزمنة، وتشخيص الأمراض الباطنية والمعدية، وتقديم الرعاية الطبية الأولية والفحوصات الدورية. متخصص في التعامل مع حالات الطوارئ والإصابات البسيطة، ويمتلك مهارة عالية في اتخاذ القرارات السريعة لتقديم الرعاية المثلى للمرضى في أقصر وقت ممكن.",
    bioEn: "General practitioner & emergency medicine specialist with extensive experience in managing acute and chronic cases, diagnosing internal and infectious diseases, and providing primary medical care and routine check-ups. Skilled in handling emergency situations and minor injuries, with a high ability to make quick decisions to provide optimal patient care in the shortest time possible."
  },
  { id: "mahmoud-zahir",
    nameAr: " د/ محمود زهير",
    nameEn: "Dr. Mahmoud Zahir",
    specialtyAr: "طبيب عام وطوارئ",
    specialtyEn: "General Practitioner & Emergency Medicine",
    degreeAr: "طبيب عام وطوارئ",
    degreeEn: "General Practitioner & Emergency Medicine",
    deptSlug: "general-er",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr: "طبيب عام وطوارئ يتمتع بخبرة واسعة في التعامل مع الحالات الحادة والمزمنة، وتشخيص الأمراض الباطنية والمعدية، وتقديم الرعاية الطبية الأولية والفحوصات الدورية. متخصص في التعامل مع حالات الطوارئ والإصابات البسيطة، ويمتلك مهارة عالية في اتخاذ القرارات السريعة لتقديم الرعاية المثلى للمرضى في أقصر وقت ممكن.",
    bioEn: "General practitioner & emergency medicine specialist with extensive experience in managing acute and chronic cases, diagnosing internal and infectious diseases, and providing primary medical care and routine check-ups. Skilled in handling emergency situations and minor injuries, with a high ability to make quick decisions to provide optimal patient care in the shortest time possible."
  },
  { id: "eman-zain",
    nameAr: " د/ ايمان زين",
    nameEn: "Dr. Eman Zain",
    specialtyAr: "طبيب عام وطوارئ",
    specialtyEn: "General Practitioner & Emergency Medicine",
    degreeAr: "طبيب عام وطوارئ",
    degreeEn: "General Practitioner & Emergency Medicine",
    deptSlug: "general-er",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr: "طبيب عام وطوارئ يتمتع بخبرة واسعة في التعامل مع الحالات الحادة والمزمنة، وتشخيص الأمراض الباطنية والمعدية، وتقديم الرعاية الطبية الأولية والفحوصات الدورية. متخصص في التعامل مع حالات الطوارئ والإصابات البسيطة، ويمتلك مهارة عالية في اتخاذ القرارات السريعة لتقديم الرعاية المثلى للمرضى في أقصر وقت ممكن.",
    bioEn: "General practitioner & emergency medicine specialist with extensive experience in managing acute and chronic cases, diagnosing internal and infectious diseases, and providing primary medical care and routine check-ups. Skilled in handling emergency situations and minor injuries, with a high ability to make quick decisions to provide optimal patient care in the shortest time possible."
  },
  { id: "eman-jamal",
    nameAr: " د/ إيمان جمال",
    nameEn: "Dr. Eman Jamal",
    specialtyAr: "طبيب عام وطوارئ",
    specialtyEn: "General Practitioner & Emergency Medicine",
    degreeAr: "طبيب عام وطوارئ",
    degreeEn: "General Practitioner & Emergency Medicine",
    deptSlug: "general-er",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr: "طبيب عام وطوارئ يتمتع بخبرة واسعة في التعامل مع الحالات الحادة والمزمنة، وتشخيص الأمراض الباطنية والمعدية، وتقديم الرعاية الطبية الأولية والفحوصات الدورية. متخصص في التعامل مع حالات الطوارئ والإصابات البسيطة، ويمتلك مهارة عالية في اتخاذ القرارات السريعة لتقديم الرعاية المثلى للمرضى في أقصر وقت ممكن.",
    bioEn: "General practitioner & emergency medicine specialist with extensive experience in managing acute and chronic cases, diagnosing internal and infectious diseases, and providing primary medical care and routine check-ups. Skilled in handling emergency situations and minor injuries, with a high ability to make quick decisions to provide optimal patient care in the shortest time possible."
  },
  { id: "khalid-aldahjam",
    nameAr: "د/ خالد الدعجم",
    nameEn: "Dr.Khalid Al-Dahjam",
    specialtyAr: " استشاري الأطفال وحديثي الولادة",
    specialtyEn: "Consultant Pediatrician & Neonatologist",
    degreeAr: "استشاري الأطفال وحديثي الولادة",
    degreeEn: "Consultant of Pediatrics & Neonatology",
    deptSlug: "pediatrics",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr: "استشاري الأطفال وحديثي الولادة. متابعة حالات الأطفال وحديثي الولادة.",
    bioEn: "Consultant pediatrician & neonatologist. Care for children and newborns."
  },
  { id: "shafia-khan",
    nameAr: " د/شافيا خان",
    nameEn: "Dr.Shafia Khan",
    specialtyAr: "أخصائية الأطفال وحديثي الولادة",
    specialtyEn: "Consultant Pediatrician & Neonatologist",
    degreeAr: "استشاري الأطفال وحديثي الولادة",
    degreeEn: "Consultant of Pediatrics & Neonatology",
    deptSlug: "pediatrics",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr: "استشاري الأطفال وحديثي الولادة. متابعة حالات الأطفال وحديثي الولادة.",
    bioEn: "Consultant pediatrician & neonatologist. Care for children and newborns."
  },
  { id: "noha-nasser",
    nameAr: "د/ نهى نصير",
    nameEn: "Dr. Noha Nasser",
    specialtyAr: "استشاري النساء والتوليد",
    specialtyEn: "Consultant OB/GYN",
    degreeAr: "استشاري النساء والتوليد",
    degreeEn: "Consultant of Obstetrics and Gynecology",
    deptSlug: "obgyn",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr: "استشاري النساء والتوليد. متابعة حالات النساء والتوليد العامة والمتقدمة وجراحة الأورام النسائية.",
    bioEn: "Consultant obstetrics & gynecology. General and advanced OB/GYN care and gynecologic oncology surgery."
  },
  { id: "nizar-mohammed",
    nameAr: "د/ نزار محمد",
    nameEn: "Dr. Nizar Mohammed",
    specialtyAr: "اخصائي تقويم الأسنان",
    specialtyEn: "Consultant Orthodontist",
    degreeAr: "استشاري تقويم الأسنان",
    degreeEn: "Consultant of Orthodontics",
    deptSlug: "dental",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr: "استشاري تقويم الأسنان. متابعة حالات تقويم الأسنان.",
    bioEn: "Consultant orthodontist. Care for orthodontic cases."
  },
  { id: "alhanouf-bin-said",
    nameAr: "د/ الهنوف بن سعيد",
    nameEn: "Dr. Alhanouf Bin Said",
    specialtyAr: "طبيب أسنان عام",
    specialtyEn: "General Dentist",
    degreeAr: "طبيب أسنان",
    degreeEn: "Doctor of Dental Medicine",
    deptSlug: "dental",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr: "طبيب أسنان عام. متابعة حالات الأسنان العامة.",
    bioEn: "General dentist. Care for general dental cases."
  },
  { id: "abdulaziz-al-mutairi",
    nameAr: "أ/ عبدالعزيز المطرفي",
    nameEn: "Mr. Abdulaziz Al-Mutairi",
    specialtyAr: "أخصائي العلاج الطبيعي",
    specialtyEn: "Consultant Physical Therapist",
    degreeAr: "استشاري العلاج الطبيعي",
    degreeEn: "Consultant of Physical Therapy",
    deptSlug: "physiotherapy",
    phone: "+966118342222",
    email: "info@healthyclinics-sa.com",
    photo: "",
    bioAr: "استشاري العلاج الطبيعي. متابعة حالات العلاج الطبيعي.",
    bioEn: "Consultant physical therapist. Care for physical therapy cases."
  }
];
