export const DOCTORS = [
  {
    id: 1,
    nameAr: "د. أحمد السالم",
    nameEn: "Dr. Ahmed Al-Salem",
    specialtyAr: "باطنة",
    specialtyEn: "Internal Medicine",
    deptSlug: "internal-med",
    photo: "/assets/doctors/internal-1.jpg",
    phone: "00966111223344",
    email: "ahmed@clinic.com",
    bioAr: "طبيب باطنة بخبرة واسعة في أمراض الجهاز الهضمي والباطنة.",
    bioEn: "Internal medicine doctor experienced in GI and internal diseases."
  },
  {
    id: 2,
    nameAr: "د. سارة العتيبي",
    nameEn: "Dr. Sarah Al-Otaibi",
    specialtyAr: "أطفال",
    specialtyEn: "Pediatrics",
    deptSlug: "pediatrics",
    photo: "/assets/doctors/pediatrics-1.jpg",
    phone: "00966111223345",
    email: "sarah@clinic.com",
    bioAr: "متخصصة في طب الأطفال ورعاية حديثي الولادة.",
    bioEn: "Specialist in pediatrics and newborn care."
  },
  {
    id: 3,
    nameAr: "د. ليلى الغامدي",
    nameEn: "Dr. Laila Al-Ghamdi",
    specialtyAr: "جلدية",
    specialtyEn: "Dermatology",
    deptSlug: "dermatology",
    photo: "/assets/doctors/dermatology-1.jpg",
    phone: "00966111223346",
    email: "laila@clinic.com",
    bioAr: "خبيرة في علاج الأمراض الجلدية والعناية بالبشرة والشعر.",
    bioEn: "Expert in dermatology, skin and hair care."
  },
  {
    id: 4,
    nameAr: "د. ماجد المطيري",
    nameEn: "Dr. Majed Al-Mutairi",
    specialtyAr: "أسنان",
    specialtyEn: "Dentistry",
    deptSlug: "dental",
    photo: "/assets/doctors/dental-1.jpg",
    phone: "00966111223347",
    email: "majed@clinic.com",
    bioAr: "يقدم خدمات شاملة لصحة الفم والأسنان.",
    bioEn: "Provides comprehensive oral and dental health services."
  },
  {
    id: 5,
    nameAr: "د. نواف الحربي",
    nameEn: "Dr. Nawaf Al-Harbi",
    specialtyAr: "عظام",
    specialtyEn: "Orthopedics",
    deptSlug: "orthopedics",
    photo: "/assets/doctors/orthopedics-1.jpg",
    phone: "00966111223348",
    email: "nawaf@clinic.com",
    bioAr: "متخصص في جراحة العظام والمفاصل والإصابات الرياضية.",
    bioEn: "Specialist in orthopedic surgery, joints and sports injuries."
  },
  {
    id: 6,
    nameAr: "د. ريم القحطاني",
    nameEn: "Dr. Reem Al-Qahtani",
    specialtyAr: "قلب",
    specialtyEn: "Cardiology",
    deptSlug: "cardiology",
    photo: "/assets/doctors/cardiology-1.jpg",
    phone: "00966111223349",
    email: "reem@clinic.com",
    bioAr: "خبيرة في أمراض القلب والأوعية الدموية.",
    bioEn: "Expert in heart and cardiovascular diseases."
  },
  {
    id: 7,
    nameAr: "د. منى الشهري",
    nameEn: "Dr. Muna Al-Shehri",
    specialtyAr: "نساء وولادة",
    specialtyEn: "Obstetrics & Gynecology",
    deptSlug: "obgyn",
    photo: "/assets/doctors/obgyn-1.jpg",
    phone: "00966111223350",
    email: "muna@clinic.com",
    bioAr: "رعاية شاملة للمرأة تشمل متابعة الحمل والولادة.",
    bioEn: "Comprehensive women’s health including pregnancy and childbirth."
  },
  {
    id: 8,
    nameAr: "د. خالد الزهراني",
    nameEn: "Dr. Khaled Al-Zahrani",
    specialtyAr: "أنف وأذن وحنجرة",
    specialtyEn: "ENT",
    deptSlug: "ent",
    photo: "/assets/doctors/ent-1.jpg",
    phone: "00966111223351",
    email: "khaled@clinic.com",
    bioAr: "متخصص في تشخيص وعلاج أمراض الأنف والأذن والحنجرة.",
    bioEn: "Specialist in diagnosis and treatment of ENT conditions."
  },
  {
    id: 9,
    nameAr: "د. عبدالعزيز الدوسري",
    nameEn: "Dr. Abdulaziz Al-Dosari",
    specialtyAr: "عيون",
    specialtyEn: "Ophthalmology",
    deptSlug: "ophthalmology",
    photo: "/assets/doctors/ophthalmology-1.jpg",
    phone: "00966111223352",
    email: "abdulaziz@clinic.com",
    bioAr: "خبير في جراحة العيون وعلاج مشاكل الإبصار.",
    bioEn: "Expert in eye surgery and vision problems."
  },
  {
    id: 10,
    nameAr: "أ. رائد الشمري",
    nameEn: "Mr. Raed Al-Shammari",
    specialtyAr: "صيدلي إكلينيكي",
    specialtyEn: "Clinical Pharmacist",
    deptSlug: "pharmacy",
    photo: "/assets/doctors/pharmacy-1.jpg",
    phone: "00966111223353",
    email: "raed@clinic.com",
    bioAr: "صيدلي إكلينيكي يقدم استشارات دوائية متخصصة.",
    bioEn: "Clinical pharmacist providing specialized drug consultations."
  },
  {
    id: 11,
    nameAr: "أ. هناء المطيري",
    nameEn: "Ms. Hanaa Al-Mutairi",
    specialtyAr: "أخصائية مختبر",
    specialtyEn: "Laboratory Specialist",
    deptSlug: "lab",
    photo: "/assets/doctors/lab-1.jpg",
    phone: "00966111223354",
    email: "hanaa@clinic.com",
    bioAr: "أخصائية مختبر بخبرة في الفحوصات الطبية والتحاليل.",
    bioEn: "Lab specialist with expertise in medical tests and diagnostics."
  },
  {
    id: 12,
    nameAr: "د. فيصل السبيعي",
    nameEn: "Dr. Faisal Al-Subaie",
    specialtyAr: "غسيل كلى",
    specialtyEn: "Dialysis",
    deptSlug: "dialysis",
    photo: "/assets/doctors/dialysis-1.jpg",
    phone: "00966111223355",
    email: "faisal@clinic.com",
    bioAr: "متخصص في رعاية مرضى الكلى وجلسات الغسيل الكلوي.",
    bioEn: "Specialist in kidney care and dialysis sessions."
  },
  {
    id: 13,
    nameAr: "د. تركي العتيق",
    nameEn: "Dr. Turki Al-Ateeq",
    specialtyAr: "طوارئ",
    specialtyEn: "Emergency Medicine",
    deptSlug: "er",
    photo: "/assets/doctors/er-1.jpg",
    phone: "00966111223356",
    email: "turki@clinic.com",
    bioAr: "طبيب طوارئ بخبرة في الحالات الحرجة والعاجلة.",
    bioEn: "Emergency physician experienced in critical and urgent cases."
  },
  {
    id: 14,
    nameAr: "د. محمد القحطاني",
    nameEn: "Dr. Mohammed Al-Qahtani",
    specialtyAr: "طب عام",
    specialtyEn: "General Medicine",
    deptSlug: "general",
    photo: "/assets/doctors/general-1.jpg",
    phone: "00966111223357",
    email: "mohammed@clinic.com",
    bioAr: "طبيب عام يقدم رعاية شاملة وتشخيص الأمراض الشائعة.",
    bioEn: "General practitioner providing comprehensive care and common disease diagnosis."
  },
  {
    id: 15,
    nameAr: "د. آلاء العبدلي",
    nameEn: "Dr. Alaa Al-Abdali",
    specialtyAr: "أشعة",
    specialtyEn: "Radiology",
    deptSlug: "radiology",
    photo: "/assets/doctors/radiology-1.jpg",
    phone: "00966111223358",
    email: "alaa@clinic.com",
    bioAr: "أخصائية أشعة بخبرة في التشخيص بالتصوير الطبي.",
    bioEn: "Radiologist experienced in medical imaging diagnosis."
  },
  {
    id: 16,
    nameAr: "د. ندى الحارثي",
    nameEn: "Dr. Nada Al-Harthi",
    specialtyAr: "علاج طبيعي",
    specialtyEn: "Physiotherapy",
    deptSlug: "physiotherapy",
    photo: "/assets/doctors/physiotherapy-1.jpg",
    phone: "00966111223359",
    email: "nada@clinic.com",
    bioAr: "أخصائية علاج طبيعي متخصصة في إعادة التأهيل.",
    bioEn: "Physiotherapist specialized in rehabilitation."
  },
  {
    id: 17,
    nameAr: "د. رشا العبدالكريم",
    nameEn: "Dr. Rasha Al-Abdulkarim",
    specialtyAr: "ليزر وتجميل",
    specialtyEn: "Laser & Aesthetics",
    deptSlug: "laser-cosmetics",
    photo: "/assets/doctors/laser-1.jpg",
    phone: "00966111223360",
    email: "rasha@clinic.com",
    bioAr: "خبيرة في الليزر والتجميل والعناية بالبشرة.",
    bioEn: "Expert in laser, aesthetics, and skin care."
  },
  {
    id: 18,
    nameAr: "أ. مي العيسى",
    nameEn: "Ms. Mai Al-Issa",
    specialtyAr: "عناية بالبشرة",
    specialtyEn: "Skin Care Specialist",
    deptSlug: "skin-care",
    photo: "/assets/doctors/skincare-1.jpg",
    phone: "00966111223361",
    email: "mai@clinic.com",
    bioAr: "أخصائية عناية بالبشرة بخبرة في العلاجات التجميلية.",
    bioEn: "Skin care specialist with expertise in cosmetic treatments."
  }
];
